// Generated by CoffeeScript 1.6.2
(function() {
  var Ball, root;

  Ball = (function() {
    function Ball() {}

    Ball.prototype.makeSomeNoice = function() {
      return alert("bump!");
    };

    return Ball;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.Ball = Ball;

}).call(this);
